version: '3.3'

services:
  mysql8:
    image: 'mysql:latest'  # download from docker hub
    container_name: 'mysql8-container'
    environment:
      - 'MYSQL_ROOT_PASSWORD=Welcome#123'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  
  customer-service:
    build: ./customer-service  # use the Dockerfile in this directory to build a new image
    container_name: customer-service-container
    depends_on:
      - mysql8
    ports:
      - '9090:9090'
    environment:
      - 'MYSQL_HOST=mysql8'
      - 'MYSQL_DB=vindb'

volumes:
  mysql_data:
    external: true  # need to create this volume manually 'docker volume create --name=mysql_data'
      